ALTER TABLE users
ADD COLUMN tenant_id UUID;

UPDATE users
SET role = CASE role
  WHEN 'ADMIN' THEN 'TENANT_ADMIN'
  WHEN 'OPERATOR' THEN 'PLATFORM_ADMIN'
  ELSE role
END;

ALTER TABLE users
DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE users
ADD CONSTRAINT users_role_check
CHECK (role IN ('CUSTOMER', 'TENANT_STAFF', 'TENANT_ADMIN', 'PLATFORM_ADMIN'));

UPDATE customers
SET role = CASE role
  WHEN 'ADMIN' THEN 'TENANT_ADMIN'
  WHEN 'OPERATOR' THEN 'PLATFORM_ADMIN'
  ELSE role
END;

ALTER TABLE customers
DROP CONSTRAINT IF EXISTS customers_role_check;

ALTER TABLE customers
ADD CONSTRAINT customers_role_check
CHECK (role IN ('CUSTOMER', 'TENANT_STAFF', 'TENANT_ADMIN', 'PLATFORM_ADMIN'));
