export const VERIFY_MAIL_TOKEN = {
  MAIL_SERVICE: 'MAIL_SERVICE',
  EMAIL_VERIFICATION_TOKEN_REPO: 'EMAIL_VERIFICATION_TOKEN_REPO',
  PASSWORD_RESET_TOKEN_REPO: 'PASSWORD_RESET_TOKEN_REPO',
  USER: 'USER_REPOSITORY',
};
